server:
  port: 9000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: eyesSpace
  datasource:
    username: dev
    password: eyesYeager@Db25@dev!
    url: jdbc:mysql://gz-cynosdbmysql-grp-lutnxlwx.sql.tencentcdb.com:29817/eyesspace_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 5
      minimum-idle: 2

eyes-auth:
  enabled: true
  app-id: space
  auth-type: 2
  thrift:
    host: 127.0.0.1
    port: 9011

eyes-storage:
  enable: true
  fail-mode: safe
  fail-retry: 2
  source:
    minio:
      enable: true
      roles:
        - read
        - write
        - delete
      endpoint: http://oss.eyescode.top
      accessKey: 63TQn6WkFI0hxYQh9oPR
      secretKey: scVyz7mEjmwROs1Er8A6IQ63235GpgSMy41DGttW
      bucket: eyesspace
    qiniu:
      enable: true
      roles:
        - write
      endpoint: http://space-cdn.eyescode.top
      accessKey: QeF_75BUrYiNOInwRWwXm2Hnq2F9QH0RzGFX-sHs
      secretKey: 4utHhcZGqXDzmLUJQ4lKSyB0sF37OpT3ZtOjoQT3
      bucket: space-cdn
      region: HuaNan
      put-compress: true

path:
  folder:
    blog: blog
    music: music
    music-cover: musicCover
    shuo: shuoshuo
    video: video
    video-cover: videoCover
    travel: travel
    joke: joke
    anime: anime
    friend: friend
    version: version